# Generated by Django 3.0.2 on 2020-01-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('field', models.CharField(choices=[('text', 'Text'), ('switch', 'Switch'), ('slider', 'Slider')], max_length=24)),
                ('prefix', models.CharField(blank=True, default='', max_length=10)),
                ('suffix', models.CharField(blank=True, default='', max_length=10)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UIs', to='iot.Device')),
            ],
        ),
    ]
