# Generated by Django 3.0.2 on 2020-01-19 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_userinterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinterface',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uis', to='iot.Device'),
        ),
        migrations.AlterField(
            model_name='userinterface',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='RaspberryGpio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(1, 'Input'), (0, 'Output')])),
                ('address', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(27)])),
                ('label', models.CharField(blank=True, max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpios', to='iot.Device')),
            ],
        ),
    ]
